export const analyticsDisclosure: Record<string, string> = {
  "tr": "GA4 ve Clarity kabul veya ret durumunda çalışır. Ret durumunda ölçüm çerezsiz ve sınırlıdır. Kabul, analitik çerezlerini ve Google Tag Manager’ı etkinleştirir. Clarity metinleri maskeler. Tercihinizi daha sonra değiştirebilirsiniz.",
  "en": "GA4 and Clarity operate whether you accept or reject. Rejection keeps measurement limited and cookieless. Acceptance enables analytics cookies and Google Tag Manager. Clarity masks text. You can change your preference later.",
  "de": "GA4 und Clarity arbeiten bei Zustimmung und Ablehnung. Bei Ablehnung erfolgt eine eingeschränkte Messung ohne Cookies. Zustimmung aktiviert Analyse-Cookies und Google Tag Manager. Clarity maskiert Texte. Sie können Ihre Auswahl später ändern.",
  "it": "GA4 e Clarity funzionano sia in caso di accettazione sia di rifiuto. Il rifiuto mantiene una misurazione limitata senza cookie. Il consenso abilita i cookie analitici e Google Tag Manager. Clarity maschera i testi. Puoi modificare la scelta in seguito.",
  "ru": "GA4 и Clarity работают как при согласии, так и при отказе. При отказе измерение ограничено и не использует cookie. Согласие включает аналитические cookie и Google Tag Manager. Clarity маскирует текст. Вы можете изменить выбор позже.",
  "fa": "GA4 و Clarity چه با پذیرش و چه با رد کار می‌کنند. در صورت رد، اندازه‌گیری محدود و بدون کوکی است. پذیرش، کوکی‌های تحلیلی و Google Tag Manager را فعال می‌کند. Clarity متن‌ها را می‌پوشاند. می‌توانید انتخاب خود را بعداً تغییر دهید.",
  "zh": "无论接受还是拒绝，GA4 和 Clarity 都会运行。拒绝时仅进行有限的无 Cookie 测量。接受后启用分析 Cookie 和 Google Tag Manager。Clarity 会遮蔽文本。您可以稍后更改选择。",
  "vi": "GA4 và Clarity hoạt động dù bạn chấp nhận hay từ chối. Khi từ chối, việc đo lường bị giới hạn và không dùng cookie. Chấp nhận sẽ bật cookie phân tích và Google Tag Manager. Clarity che văn bản. Bạn có thể thay đổi lựa chọn sau.",
  "sq": "GA4 dhe Clarity funksionojnë si kur pranoni, ashtu edhe kur refuzoni. Refuzimi lejon vetëm matje të kufizuar pa cookie. Pranimi aktivizon cookie analitike dhe Google Tag Manager. Clarity maskon tekstin. Mund ta ndryshoni zgjedhjen më vonë.",
  "mk": "GA4 и Clarity работат и при прифаќање и при одбивање. При одбивање мерењето е ограничено и без колачиња. Прифаќањето ги активира аналитичките колачиња и Google Tag Manager. Clarity го маскира текстот. Изборот може да го промените подоцна.",
  "sr": "GA4 i Clarity rade i kada prihvatite i kada odbijete. Pri odbijanju merenje je ograničeno i bez kolačića. Prihvatanje omogućava analitičke kolačiće i Google Tag Manager. Clarity maskira tekst. Izbor možete promeniti kasnije.",
  "ro": "GA4 și Clarity funcționează atât la acceptare, cât și la refuz. La refuz, măsurarea este limitată și fără cookie-uri. Acceptarea activează cookie-urile analitice și Google Tag Manager. Clarity maschează textul. Puteți modifica alegerea ulterior.",
  "bg": "GA4 и Clarity работят както при приемане, така и при отказ. При отказ измерването е ограничено и без бисквитки. Приемането активира аналитични бисквитки и Google Tag Manager. Clarity маскира текста. Можете да промените избора си по-късно.",
  "ka": "GA4 და Clarity მუშაობს თანხმობისა და უარის შემთხვევაშიც. უარისას გაზომვა შეზღუდულია და ქუქიებს არ იყენებს. თანხმობა ააქტიურებს ანალიტიკურ ქუქიებსა და Google Tag Manager-ს. Clarity ტექსტს ნიღბავს. არჩევანის შეცვლა მოგვიანებითაც შეგიძლიათ.",
  "az": "GA4 və Clarity qəbul və ya rədd zamanı işləyir. Rədd zamanı ölçüm kukisiz və məhduddur. Qəbul analitik kukiləri və Google Tag Manager-i aktivləşdirir. Clarity mətnləri maskalayır. Seçiminizi sonradan dəyişə bilərsiniz."
};
